name: ipc_guider
description: Offline-first IPC app (calculators, isolation & PPE, protocols, bundles).
publish_to: "none"
version: 1.1.1+3

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State & Routing
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.1

  # Local storage & prefs
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3

  # Files, export, share
  excel: ^4.0.6
  csv: ^6.0.0
  path_provider: ^2.1.4
  share_plus: ^10.1.4
  permission_handler: ^12.0.1

  # UI helpers
  flutter_svg: ^2.0.10+1
  percent_indicator: ^4.2.3
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0

  # Intl & localization (English now, Arabic later)
  intl: ^0.20.2

  # Optional: capture widgets as images (signage)
  screenshot: ^3.0.0
  url_launcher: ^6.3.2
  flutter_math_fork: ^0.7.4
  uuid: ^4.5.1
  pdf: ^3.11.3
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/data/calculator/
    - assets/data/outbreak_groups/
    - assets/data/outbreak_groups/bacterial/
    - assets/data/outbreak_groups/viral/
    - assets/data/cds/
    - assets/data/outbreak_groups/fungal/
    - assets/data/stewardship/
    - assets/icons/
    - assets/images/

# App Icon Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ipc_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/ipc_icon.png"
    background_color: "#1a2332"
    theme_color: "#2196F3"
  windows:
    generate: true
    image_path: "assets/icons/ipc_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/ipc_icon.png"
